name: webfeed
version: 0.7.0
description: webfeed is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication namespaces are also supported.
homepage: https://github.com/witochandra/webfeed
environment:
  sdk: ^3.5.0
dependencies:
  xml: ^6.5.0
  intl: ^0.19.0
dev_dependencies:
  test: ^1.25.14
  http: ^1.2.1
