name: webfeed
version: 0.7.2
description: A robust dart package for parsing RSS and Atom feeds with enhanced compatibility for a wide variety of feed formats. Supports Media, DublinCore, iTunes, and Syndication namespaces.
homepage: https://github.com/witochandra/webfeed
environment:
  sdk: ^3.5.0
dependencies:
  xml: ^6.5.0
  intl: any
  html_unescape: ^2.0.0
dev_dependencies:
  test: ^1.26.2
  http: ^1.2.1
