name: webfeed
version: 0.8.0
description: A robust dart package for parsing RSS and Atom feeds with enhanced compatibility for a wide variety of feed formats. Supports Media, DublinCore, iTunes, and Syndication namespaces.
homepage: https://github.com/witochandra/webfeed
environment:
  sdk: ^3.5.0
dependencies:
  xml: ^6.5.0
  intl: ^0.19.0
dev_dependencies:
  test: ^1.25.14
  http: ^1.2.1
